### ISSUE TITLE
nameerror

### ISSUE THREAD

**Issue by cuijing111** [EtPan/N-Net#1]
transform = [AddStripeNoiseH(),AddStripeNoiseW(),AddMixedNoiseH(),AddMixedNoiseW()]
NameError: name 'AddStripeNoiseH' is not defined.
what can I do?

**Comment by EtPan** [comment]
We do not use these transforms here. Maybe this code you quote comes from https://github.com/EtPan/PHID, where they are defined in "data/datasyn.py".

**Comment by EtPan** [comment]
> We do not use these transforms here. Maybe this code you quote comes from https://github.com/EtPan/PHID, where they are defined in "data/datasyn.py".
